### ISSUE TITLE
I think info should be ASN.1 DER TLV for the combiner OID

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-kem#16]
Motivation: converting the ASCII name of the OID to bytes could be a source interop problems.
Comment from Ilari: https://mailarchive.ietf.org/arch/msg/spasm/JUISSb8kzHvly6iwEaY4jYGG_yE/

**Comment by ounsworth** [comment]
It is worth putting an EDNOTE in the document that once we do this, we will need IANA to pre-allocate the OIDs so that we can re-compile the domain separators and update the table in the doc.
(and also put the same EDNOTE in composite-sigs)

**Comment by ounsworth** [comment]
Do we actually have a domain separators table at all? ADD ONE.

**Comment by johngray-dev** [comment]
Align with composite signatures with a similar table for domain separators (DER encoded OID values).

**Comment by johngray-dev** [comment]
Added table in section 2.5, and also updated the definition of the fixedInfo value.   See Merge here:  https://github.com/lamps-wg/draft-composite-kem/commit/e9db1fa3e40edcca15acbee1d19db1c3b7ea9089
