### ISSUE TITLE
Should we instead or in addition support RSA-OAEP?

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-kem#21]
Sophie Schmieg made the excellent point:

> on the classical side, nobody uses RSA-KEM (a shame, but alas), leaving RSA-OAEP

**Comment by ounsworth** [comment]
What about RSA-PKCS#1 ?

**Comment by johngray-dev** [comment]
Asking Lamps WG about this at the IETF 120 presentation
