### ISSUE TITLE
Drop DER encoding

### ISSUE THREAD

**Issue by chris-wood** [lamps-wg/draft-composite-kem#88]
An implementation of these KEMs should _not_ need any DER encoding or parsing logic to function. The spec should drop all use of DER encoding for KEM public keys and ciphertexts. Applications or protocols which require DER can wrap them as desired, but for the relevant hybrids here, they are simply not needed and add unnecessary complexity.

**Comment by ounsworth** [comment]
Yup. We will do this. It's become clear in the past few weeks that non-PKIX protocols would like to directly re-use our construction.

**Comment by chris-wood** [comment]
Great! Do you want PRs for this, or do you intend to make the change yourself?

**Comment by johngray-dev** [comment]
I was planning to remove the DER encoding for both this draft and the composite Signatures draft.   Thanks for suggesting edits, I'll take a look at them.
