### ISSUE TITLE
Drop id-MLKEM768-X25519

### ISSUE THREAD

**Issue by ilaril** [lamps-wg/draft-composite-kem#90]
As far as I can tell, this is just an incompatible (different domain) duplicate of the X-Wing.

It would be easier for crypto implementers to just have one construction to combine X25519 and MLKEM768, not two.

**Comment by ounsworth** [comment]
Ilari, were you in LAMPS? This point was discussed fairly extensively.

Currently this combination IS X-Wing (or at least, it is attempting to be), and as such, I am very confused about why the X-Wing draft bothered to include OIDs. Currently the only (substantial) difference between this and X-Wing is their "simultaneous KeyGen". We are in discussions with the X-Wing authors about whether we want them to be separate or not.

**Comment by ounsworth** [comment]
Since this is an open discussion point, I am going to remove this github issue.

**Comment by ilaril** [comment]
There is another substantial difference besides the keygen: The domain separators are different (060B6086480186FA6B5005021A versus 5c2e2f2f5e5c). So changing the object identifier in public key does not work (whereas it would if the only difference was the keygen).

Re-watching the session recording, the closest comments I can find are about having two close things being a bad idea, and the keygen difference justifying a new object identifier.
